stock_list = [
    "ABB",
    "ACC",
    "AUBANK",
    "ABBOTINDIA",
    "ADANIENT",
    "ADANIGREEN",
    "ADANIPORTS",
    "ATGL",
    "ADANITRANS",
    "ABCAPITAL",
    "ABFRL",
    "APLLTD",
    "ALKEM",
    "AMBUJACEM",
    "APOLLOHOSP",
    "APOLLOTYRE",
    "ASHOKLEY",
    "ASIANPAINT",
    "ASTRAL",
    "AUROPHARMA",
    "DMART",
    "AXISBANK",
    "BAJAJ-AUTO",
    "BAJFINANCE",
    "BAJAJFINSV",
    "BAJAJHLDNG",
    "BALKRISIND",
    "BANDHANBNK",
    "BANKBARODA",
    "BANKINDIA",
    "BATAINDIA",
    "BERGEPAINT",
    "BEL",
    "BHARATFORG",
    "BHEL",
    "BPCL",
    "BHARTIARTL",
    "BIOCON",
    "BOSCHLTD",
    "BRITANNIA",
    "CANBK",
    "CHOLAFIN",
    "CIPLA",
    "CLEAN",
    "COALINDIA",
    "COFORGE",
    "COLPAL",
    "CONCOR",
    "COROMANDEL",
    "CROMPTON",
    "CUMMINSIND",
    "DLF",
    "DABUR",
    "DALBHARAT",
    "DEEPAKNTR",
    "DIVISLAB",
    "DIXON",
    "LALPATHLAB",
    "DRREDDY",
    "EICHERMOT",
    "EMAMILTD",
    "ESCORTS",
    "EXIDEIND",
    "NYKAA",
    "FEDERALBNK",
    "FORTIS",
    "GAIL",
    "GLAND",
    "GLENMARK",
    "GODREJCP",
    "GODREJPROP",
    "GRASIM",
    "GUJGASLTD",
    "GSPL",
    "HCLTECH",
    "HDFCAMC",
    "HDFCBANK",
    "HDFCLIFE",
    "HAVELLS",
    "HEROMOTOCO",
    "HINDALCO",
    "HAL",
    "HINDPETRO",
    "HINDUNILVR",
    "HINDZINC",
    "HONAUT",
    "HDFC",
    "ICICIBANK",
    "ICICIGI",
    "ICICIPRULI",
    "ISEC",
    "IDBI",
    "IDFCFIRSTB",
    "ITC",
    "INDIAMART",
    "INDIANB",
    "IEX",
    "INDHOTEL",
    "IOC",
    "IRCTC",
    "IGL",
    "INDUSTOWER",
    "INDUSINDBK",
    "NAUKRI",
    "INFY",
    "INDIGO",
    "IPCALAB",
    "JSWENERGY",
    "JSWSTEEL",
    "JINDALSTEL",
    "JUBLFOOD",
    "KOTAKBANK",
    "L&TFH",
    "LTTS",
    "LICHSGFIN",
    "LTI",
    "LT",
    "LAURUSLABS",
    "LUPIN",
    "MRF",
    "M&MFIN",
    "M&M",
    "MANAPPURAM",
    "MARICO",
    "MARUTI",
    "MFSL",
    "MAXHEALTH",
    "METROPOLIS",
    "MINDTREE",
    "MPHASIS",
    "MUTHOOTFIN",
    "NMDC",
    "NTPC",
    "NATIONALUM",
    "NAVINFLUOR",
    "NESTLEIND",
    "NAM-INDIA",
    "OBEROIRLTY",
    "ONGC",
    "OIL",
    "PAYTM",
    "OFSS",
    "POLICYBZR",
    "PIIND",
    "PAGEIND",
    "PERSISTENT",
    "PETRONET",
    "PIDILITIND",
    "PEL",
    "POLYCAB",
    "PFC",
    "POWERGRID",
    "PRESTIGE",
    "PGHH",
    "PNB",
    "RECLTD",
    "RELIANCE",
    "SBICARD",
    "SBILIFE",
    "SRF",
    "SHREECEM",
    "SRTRANSFIN",
    "SIEMENS",
    "SONACOMS",
    "SBIN",
    "SAIL",
    "SUNPHARMA",
    "SUNTV",
    "SYNGENE",
    "TVSMOTOR",
    "TATACHEM",
    "TATACOMM",
    "TCS",
    "TATACONSUM",
    "TATAELXSI",
    "TATAMOTORS",
    "TATAPOWER",
    "TATASTEEL",
    "TECHM",
    "RAMCOCEM",
    "TITAN",
    "TORNTPHARM",
    "TORNTPOWER",
    "TRENT",
    "TRIDENT",
    "UPL",
    "ULTRACEMCO",
    "UNIONBANK",
    "UBL",
    "MCDOWELL-N",
    "VBL",
    "VEDL",
    "IDEA",
    "VOLTAS",
    "WHIRLPOOL",
    "WIPRO",
    "YESBANK",
    "ZEEL",
    "ZOMATO",
    "ZYDUSLIFE",
]

stock_info_dict = {
    "zip": "560058",
    "sector": "Industrials",
    "fullTimeEmployees": 3149,
    "longBusinessSummary": "ABB India Limited develops and sells products and system solutions to utilities, industries, channel partners, and original equipment manufacturers in India and internationally. The company operates through Motion, Robotics and Discrete Automation, Electrification, and Process Automation segments. The Motion segment produces and provides motors, generators, and drives that provide power, motion, and control for a range of automation applications; and offers solutions and related services. The Robotics and Discrete Automation segment provides value-added solutions in robotics, machine, and factory automation. The Electrification segment offers a range of digital and connected solutions for low- and medium-voltage applications, including EV infrastructure, solar inverters, modular substations, distribution automation, power protection, wiring accessories, switchgear, enclosures, cabling, sensing, and control products. The Process Automation segment provides products, systems, and services, such as turnkey engineering, control systems, measurement products, life cycle services, outsourced maintenance, and industry specific products for the optimization of the productivity of industrial processes in oil and gas, power, chemicals and pharmaceuticals, pulp and paper, metals and minerals, marine, and turbocharging industries. The company was formerly known as ABB Limited and changed its name to ABB India Limited in June 2013. ABB India Limited was incorporated in 1949 and is based in Bengaluru, India. ABB India Limited is a subsidiary of ABB Asea Brown Boveri Ltd.",
    "city": "Bengaluru",
    "phone": "91 80 2294 9150",
    "country": "India",
    "companyOfficers": [],
    "website": "https://new.abb.com/indian-subcontinent",
    "maxAge": 1,
    "address1": "Plot No. 5 & 6, 2nd Stage",
    "fax": "91 80 2294 9148",
    "industry": "Specialty Industrial Machinery",
    "address2": "Disha - 3rd Floor Peenya Industrial Area IV Peenya",
    "ebitdaMargins": 0.080699995,
    "profitMargins": 0.06292,
    "grossMargins": 0.32961,
    "operatingCashflow": None,
    "revenueGrowth": 0.212,
    "operatingMargins": 0.07014,
    "ebitda": 5874800128,
    "targetLowPrice": 915,
    "recommendationKey": "hold",
    "grossProfits": 22721300000,
    "freeCashflow": None,
    "targetMedianPrice": 1380,
    "currentPrice": 2315.75,
    "earningsGrowth": -0.436,
    "currentRatio": None,
    "returnOnAssets": None,
    "numberOfAnalystOpinions": 25,
    "targetMeanPrice": 1385.32,
    "debtToEquity": 0.906,
    "returnOnEquity": None,
    "targetHighPrice": 2050,
    "totalCash": 26851399680,
    "totalDebt": 366600000,
    "totalRevenue": 72797102080,
    "totalCashPerShare": 126.712,
    "financialCurrency": "INR",
    "revenuePerShare": 343.542,
    "quickRatio": None,
    "recommendationMean": 3.5,
    "exchange": "NSI",
    "shortName": "ABB INDIA LTD",
    "longName": "ABB India Limited",
    "exchangeTimezoneName": "Asia/Kolkata",
    "exchangeTimezoneShortName": "IST",
    "isEsgPopulated": False,
    "gmtOffSetMilliseconds": "19800000",
    "quoteType": "EQUITY",
    "symbol": "ABB.NS",
    "messageBoardId": "finmb_878520",
    "market": "in_market",
    "annualHoldingsTurnover": None,
    "enterpriseToRevenue": 6.377,
    "beta3Year": None,
    "enterpriseToEbitda": 79.023,
    "52WeekChange": 0.37380242,
    "morningStarRiskRating": None,
    "forwardEps": 35.36,
    "revenueQuarterlyGrowth": None,
    "sharesOutstanding": 211908000,
    "fundInceptionDate": None,
    "annualReportExpenseRatio": None,
    "totalAssets": None,
    "bookValue": 190.893,
    "sharesShort": None,
    "sharesPercentSharesOut": None,
    "fundFamily": None,
    "lastFiscalYearEnd": 1640908800,
    "heldPercentInstitutions": 0.10663,
    "netIncomeToCommon": 4585999872,
    "trailingEps": 21.616,
    "lastDividendValue": 5.2,
    "SandP52WeekChange": -0.027914226,
    "priceToBook": 12.131142,
    "heldPercentInsiders": 0.75,
    "nextFiscalYearEnd": 1703980800,
    "yield": None,
    "mostRecentQuarter": 1648684800,
    "shortRatio": None,
    "sharesShortPreviousMonthDate": None,
    "floatShares": 52451561,
    "beta": 0.927319,
    "enterpriseValue": 464242016256,
    "priceHint": 2,
    "threeYearAverageReturn": None,
    "lastSplitDate": 1182988800,
    "lastSplitFactor": "5:1",
    "legalType": None,
    "lastDividendDate": 1651104000,
    "morningStarOverallRating": None,
    "earningsQuarterlyGrowth": -0.436,
    "priceToSalesTrailing12Months": 6.750489,
    "dateShortInterest": None,
    "pegRatio": 3.01,
    "ytdReturn": None,
    "forwardPE": 65.49067,
    "lastCapGain": None,
    "shortPercentOfFloat": None,
    "sharesShortPriorMonth": None,
    "impliedSharesOutstanding": 0,
    "category": None,
    "fiveYearAverageReturn": None,
    "previousClose": 2418.4,
    "regularMarketOpen": 2427,
    "twoHundredDayAverage": 2108.115,
    "trailingAnnualDividendYield": 0.002150182,
    "payoutRatio": 0.23110001,
    "volume24Hr": None,
    "regularMarketDayHigh": 2449.95,
    "navPrice": None,
    "averageDailyVolume10Day": 226314,
    "regularMarketPreviousClose": 2418.4,
    "fiftyDayAverage": 2197.646,
    "trailingAnnualDividendRate": 5.2,
    "open": 2427,
    "toCurrency": None,
    "averageVolume10days": 226314,
    "expireDate": None,
    "algorithm": None,
    "dividendRate": 5.2,
    "exDividendDate": 1651104000,
    "circulatingSupply": None,
    "startDate": None,
    "regularMarketDayLow": 2307.85,
    "currency": "INR",
    "trailingPE": 107.131294,
    "regularMarketVolume": 195078,
    "lastMarket": None,
    "maxSupply": None,
    "openInterest": None,
    "marketCap": 491416059904,
    "volumeAllCurrencies": None,
    "strikePrice": None,
    "averageVolume": 283099,
    "dayLow": 2307.85,
    "ask": 0,
    "askSize": 0,
    "volume": 195078,
    "fiftyTwoWeekHigh": 2487.85,
    "fromCurrency": None,
    "fiveYearAvgDividendYield": None,
    "fiftyTwoWeekLow": 1601,
    "bid": 0,
    "tradeable": False,
    "dividendYield": 0.0022,
    "bidSize": 0,
    "dayHigh": 2449.95,
    "regularMarketPrice": 2315.75,
    "logo_url": "https://logo.clearbit.com/new.abb.com",
}
